@API_HostAddress = http://localhost:5270

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{API_HostAddress}}/api/products/
Accept: application/json
###

GET {{API_HostAddress}}/api/products/?brand=Angular
Accept: application/json
###

GET {{API_HostAddress}}/api/products/?sort=priceDesc
Accept: application/json
###

GET {{API_HostAddress}}/api/products/2
Accept: application/json
###

POST {{API_HostAddress}}/api/products/
Content-Type: application/json

{
    "Name" : "what",
    "Description" : "Lol hallo",
    "Price": 10000,
    "PictureUrl": "http://example.com/image.jpg",
    "Type": "Homeware",
    "Brand": "BrandyCane",
    "QuantityInStock": 25
}
###

PUT {{API_HostAddress}}/api/products/3
Content-Type: application/json

{   
    "Id" : "3",
    "Name" : "Totally different",
    "Description" : "Lol goodbye",
    "Price": 10000,
    "PictureUrl": "http://example.com/image.jpg",
    "Type": "Cars",
    "Brand": "BrandyCane",
    "QuantityInStock": 25
}
###

DELETE {{API_HostAddress}}/api/products/1003
Content-Type: application/json
###

GET {{API_HostAddress}}/api/products/brands/
Accept: application/json
###

GET {{API_HostAddress}}/api/products/brands/?brand=Angular
Accept: application/json
###

GET {{API_HostAddress}}/api/products/types/
Accept: application/json
###
